<!-- about the station -->

<div class="widget">
  <table class="about">
    <tr>
      <td class="label">Software:</td>
      <td class="data">$station.hardware</td>
    </tr>
    <tr>
      <td class="label">WeeWx uptime:</td>
      <td class="data">$station.uptime</td>
    </tr>
    <tr>
      <td class="label">Server uptime:</td>
      <td class="data">$station.os_uptime</td>
    </tr>
    <tr>
      <td class="label">WeeWX version:</td>
      <td class="data">$station.version</td>
    </tr>
  </table>
</div>
