<div id="station_info" class="widget">
  <div class="section_heading">
    $Extras.labels.station_info
  </div>

  <table class="about">
    <tr>
      <td class="label">Hardware</td>
      <td class="data">$station.hardware</td>
    </tr>
    <tr>
      <td class="label">Software</td>
      <td class="data">WeeWX $station.version</td>
    </tr>
    <tr>
      <td class="label">WeeWx uptime</td>
      <td class="data">$station.uptime</td>
    </tr>
    <tr>
      <td class="label">Server uptime</td>
      <td class="data">$station.os_uptime</td>
    </tr>
  </table>
</div>
