#!/bin/bash

# Number of seconds without weewx records before taking action
watchdogsecs=600 # 10 minutes

# e-mail address to notify
email="nobody@example.com"

# Main weewx log file
weewx_main_log=/var/log/syslog

# Supplemental log
weewx_maint_log="/var/log/weewx.log"

#############################
# Rain Counter Warning
# Check if rain counter is above warning level and notify
grep -q 'weewx.*rain counter above warning level' $weewx_main_log && \
	echo `date` "WeeWX: Rain counter above warning level!  E-mail notification sent to ${email}." >>$weewx_maint_log && \
	echo "Recommend resetting..." | mailx -s "WeeWX: Rain counter above warning level!" $email


#############################
# Wunderfixer Maintenance
# Run Wunderfixer yesterday and today (intentional overlapping, to be extra sure to catch missed uploads)
currstamp="$(date +%s)"
yesterdaystamp="$((currstamp - 86400))"
yesterday=$(date -d @$yesterdaystamp +\%Y-\%m-\%d)
/usr/share/weewx/wunderfixer --date $yesterday --verbose 2>&1 | sed "s/^/`date` /" >>$weewx_maint_log
/usr/share/weewx/wunderfixer --date `date +\%Y-\%m-\%d` --verbose 2>&1 | sed "s/^/`date` /" >>$weewx_maint_log


#############################
# Hung Station Detection
# Get the timestamp of the last time weewx logged a record
logstamp="$(sed -n 's/.*weewx.*Added record.*(\([0-9]*\)) to database.*/\1/p' ${weewx_main_log}.1 ${weewx_main_log} | tail -1)"

# Get the current timestamp since the epoc
currstamp="$(date +%s)"

# Calculate the difference between timestamp and logstamp
diffsecs=$((currstamp - logstamp))

# Check if it's been too long since last update and reboot host if necessary
if [ $diffsecs -gt $watchdogsecs ] ; then
	logger -i "weewx_watchdog: $diffsecs seconds have passed since weewx logged any records!  Rebooting!"
        echo "Reboot initiated at $(date)" | mailx -s "WeeWX: Watchdog reboot!" $email
        echo `date` "WeeWX: Watchdog reboot notification sent to ${email} and reboot initiated." >>$weewx_maint_log
	sleep 10
	exec /sbin/shutdown -r now
fi
